# Welcome to Jekyll!

# Website settings
title: Lusifer
description: Lusifer's blog,use Jekyll and github pages.
keywords: 'Lusifer,blog,Jekyll,github'
baseurl: ''
url: 'https://topsale.github.io'
# url: "http://127.0.0.1:4000"
img_path: '/static/img/blog'

# author
author:
  name: 'Lusifer'
  first_name: 'Li'
  last_name: 'WeiMin'
  cv: 'https://topsale.github.io'
  email: 'topsale@vip.qq.com'
  facebook_username: 'topsale'
  github_username: 'funtl'
  avatar: '/static/img/landing/Lusifer.jpg'
  desc: '匮乏即是富足，自律产生喜悦'

# comment
changyan:
  # appid: cysfY7ULn
  # conf: prod_861928934cecb7a18e15bedaed9dae29
disqus:
  name: jalpc
  public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7

# share
bshare:
  uuid: 513f778e-a8f7-4c20-9ec2-d29cc2328d75

# baidu analytics
ba:
  # uuid: 317acca9ef9255b934e46371e471431d

# google analytics
ga:
  id: UA-73784599-1

# growingIO
gio:
  id: a49d4901c7853da9

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
